killbill/killbill-api

src/main/java/org/killbill/billing/ErrorCode.java
src/main/java/org/killbill/billing/entitlement/api/EntitlementApi.java
src/main/java/org/killbill/billing/entitlement/api/EntitlementSpecifier.java

Combo call to create subscriptions with add-ons.

Adding a new method to fix #199

---

NEWS
src/main/java/org/killbill/billing/ErrorCode.java
src/main/java/org/killbill/billing/usage/api/SubscriptionUsageRecord.java
src/main/java/org/killbill/billing/usage/api/UsageApiException.java
src/main/java/org/killbill/billing/usage/api/UsageUserApi.java

https://github.com/killbill/killbill/issues/502

Usage API idempotency

---

src/main/java/org/killbill/billing/account/api/AccountData.java
src/main/java/org/killbill/billing/account/api/MutableAccountData.java

- Added set and get methods for new attribute "notes" in the Account object

Issue #72 - Notes for account

---

src/main/java/org/killbill/billing/ErrorCode.java

- New ErrorCode added to manage the limitation of plans allowed per bundle

Issue #545 - PlansAllowedInBundle

---

src/main/java/org/killbill/billing/payment/api/PaymentApi.java

- Added new method to get a Payment Transaction by Id

Issue #599 - Fix payment api to allow retrieving payment transaction tags

---

src/main/java/org/killbill/billing/entitlement/api/BaseEntitlementWithAddOnsSpecifier.java
src/main/java/org/killbill/billing/entitlement/api/EntitlementApi.java

- Added new BaseEntitlementWithAddOnsSpecifier to group multiple bundles.
- Added method to the EntitlementApi to create multiple entitlements with Add Ons.

Issue 219 - Create shopping cart API

---

NEWS
src/main/java/org/killbill/billing/invoice/api/InvoiceUserApi.java

See https://github.com/killbill/killbill/issues/888.

invoice: pass itemDetails to insertCredit, insertCreditForInvoice and insertInvoiceItemAdjustment APIs

---

src/main/java/org/killbill/billing/ErrorCode.java

See https://github.com/killbill/killbill/issues/893.

ErrorCode: add INVOICE_PLUGIN_API_ABORTED

---

src/main/java/org/killbill/billing/entitlement/api/EntitlementApi.java

Ref. killbill/killbill-admin-ui#137

 Proposed implementation to address issue killbill/killbill-admin-ui#137

---

src/main/java/org/killbill/billing/util/audit/AccountAuditLogs.java

Ref. killbill/killbill#937
Ref. killbill/killbill#948

 New method to get all audit logs for an account killbill/killbill#937

---

src/main/java/org/killbill/billing/account/api/AccountUserApi.java
src/main/java/org/killbill/billing/util/audit/AuditLogWithHistory.java

ref. killbill/killbill#335
ref. killbill/killbill#957

New API to retrieve history info from any objects 

---

src/main/java/org/killbill/billing/account/api/AccountUserApi.java
src/main/java/org/killbill/billing/payment/api/PaymentApi.java
src/main/java/org/killbill/billing/util/api/CustomFieldUserApi.java
src/main/java/org/killbill/billing/util/api/TagUserApi.java

ref. killbill/killbill#335
ref. killbill/killbill#972
Account Email
Payment 
Payment Method
Payment Attempts
Payment Transactions
Tag
Tag Definitions
Custom Fields

 New API to retrieve history info from any objects 

---

src/main/java/org/killbill/billing/catalog/api/Catalog.java
src/main/java/org/killbill/billing/catalog/api/StaticCatalog.java

* Remove unused APIs
* Add missing dates for grand-fathering
See https://github.com/killbill/killbill/issues/784.

Catalog APIs review 

---

src/main/java/org/killbill/billing/invoice/api/InvoicePayment.java
src/main/java/org/killbill/billing/invoice/api/InvoicePaymentApi.java
src/main/java/org/killbill/billing/invoice/api/InvoicePaymentType.java
src/main/java/org/killbill/billing/osgi/api/OSGIKillbill.java
src/main/java/org/killbill/billing/payment/api/InvoicePaymentApi.java

See https://github.com/killbill/killbill/issues/981.

API changes for 981

---

src/main/java/org/killbill/billing/payment/api/InvoicePaymentApi.java

payment: add missing chargeback APIs in InvoicePaymentApi

---

NEWS
src/main/java/org/killbill/billing/security/api/SecurityApi.java

See https://github.com/killbill/killbill/issues/1126.

security: make SecurityApi#getCurrentUserPermissions return Set<String>

---

src/main/java/org/killbill/billing/ErrorCode.java

See https://github.com/killbill/killbill/issues/1201.

ErrorCode: add error message to SUB_CREATE_INVALID_ENTITLEMENT_SPECIFIER

---

src/main/java/org/killbill/billing/invoice/api/InvoiceItem.java
src/main/java/org/killbill/billing/usage/api/RawUsageRecord.java
src/main/java/org/killbill/billing/usage/api/RolledUpUnit.java
src/main/java/org/killbill/billing/usage/api/UsageRecord.java

Pull request for [issue 1469](https://github.com/killbill/killbill/issues/1469).

Fix 1469 api usage amount should be a floating point

---

src/main/java/org/killbill/billing/catalog/api/Block.java
src/main/java/org/killbill/billing/catalog/api/BlockPriceOverride.java
src/main/java/org/killbill/billing/catalog/api/Limit.java
src/main/java/org/killbill/billing/catalog/api/PlanPhase.java
src/main/java/org/killbill/billing/catalog/api/Product.java
src/main/java/org/killbill/billing/catalog/api/TieredBlock.java
src/main/java/org/killbill/billing/catalog/api/TieredBlockPriceOverride.java
src/main/java/org/killbill/billing/catalog/api/Usage.java

affected classes and attributes described in this comment: https://github.com/killbill/killbill/issues/1469#issuecomment-1028580177

change catalog's Blocks and Limit data type from Double to BigDecimal

---

src/main/java/org/killbill/billing/catalog/api/BillingPeriod.java

Adding more billing options while creating new catalog
1. THIRTY_ONE_DAYS
2. SESQUIENNIAL
3. TRIENNIAL

New Catalog - Add more billing period options

---

src/main/java/org/killbill/billing/ErrorCode.java

Needs to be merged after https://github.com/killbill/killbill-api/pull/112

ErrorCode: Add missing error code. See killbill/killbill#1501
